name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - '.github/workflows/**'
      - '.env'
      - 'src/server.ts'
      - 'src/app.ts'
      - '__tests__/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Set MongoDB URI
        run: echo "MONGO_URL=mongodb://localhost:27017/testdb" >> $GITHUB_ENV &&
          echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
      - name: Test
        run: CI=true pnpm test 
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/edtech:latest
